# This is a basic workflow to help you get started with Actions

name: MkDocs CI

on:
  push:
    branches: [ master, docs ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Pip
      run:  python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install mkdocs && pip install mkdocs-material markdown-include

    - name: Build docs
      run:  python -m mkdocs build

    - name: Deploy MkDocs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.17
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXTRA_PACKAGES: "gcc libxml2-dev libxslt-dev musl-dev"
